import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Markdonw a HTML",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} font-sans bg-background text-foreground`}>
        <div className="min-h-screen flex flex-col page">
          <header className="hero">
            <h1>Markdown a HTML</h1>
            <p className="hero__subtitle">
              Adaptado desde el README original de un proyecto creado con NextJS.
            </p>
          </header>
          <main className="content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
